import { AlertCircle, CheckCircle2, Github, RefreshCw } from "lucide-react";
import { useGithubSync } from "../../hooks/useGithubSync";
import { GITHUB_REPOSITORY } from "../../services/githubSubmissionService";

const formatSyncTime = (value?: string) => value ? new Date(value).toLocaleString(undefined, { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }) : "Not synced yet";

export function GithubIntegration() {
  const { cache, syncing, sync } = useGithubSync();
  const connected = Boolean(cache.lastSyncAt) && !cache.lastError;
  const status = connected ? "Connected" : cache.lastError ? cache.lastSyncAt ? "Using cached data" : "Sync unavailable" : "Ready to sync";
  return <section className="panel mt-6 p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="subtle-label">GitHub integration</p><h2 className="mt-1 text-xl font-semibold text-slate-100">Submission sync</h2><p className="mt-2 text-sm text-slate-400">Public repository: <span className="font-medium text-slate-200">{GITHUB_REPOSITORY}</span></p></div><Github className="text-slate-400" size={23} /></div><div className="mt-6 grid gap-3 text-sm sm:grid-cols-2"><div className="rounded-xl bg-slate-950/30 p-3"><p className="text-slate-500">Status</p><p className={`mt-1 inline-flex items-center gap-1.5 font-medium ${connected ? "text-emerald-300" : "text-amber-300"}`}>{connected ? <CheckCircle2 size={15} /> : <AlertCircle size={15} />}{status}</p></div><div className="rounded-xl bg-slate-950/30 p-3"><p className="text-slate-500">Last synced</p><p className="mt-1 font-medium text-slate-200">{formatSyncTime(cache.lastSyncAt)}</p></div><div className="rounded-xl bg-slate-950/30 p-3"><p className="text-slate-500">Problems discovered</p><p className="mt-1 font-medium text-slate-200">{cache.discoveredProblems.length}</p></div><div className="rounded-xl bg-slate-950/30 p-3"><p className="text-slate-500">Submissions discovered</p><p className="mt-1 font-medium text-slate-200">{cache.submissions.length}</p></div></div>{cache.lastError && <p role="status" className="mt-4 rounded-lg border border-amber-400/25 bg-amber-400/10 px-3 py-2.5 text-sm text-amber-100">{cache.lastError.message}</p>}{cache.unmappedRepositorySlugs.length > 0 && <details className="mt-4 rounded-lg border border-slate-700 px-3 py-2.5 text-sm"><summary className="cursor-pointer font-medium text-amber-200">Review mappings · {cache.unmappedRepositorySlugs.length} repository {cache.unmappedRepositorySlugs.length === 1 ? "problem could" : "problems could"} not be mapped</summary><p className="mt-2 text-slate-400">Add explicit entries to <code className="rounded bg-slate-800 px-1.5 py-0.5">src/data/repositoryMappings.json</code> to include them.</p><p className="mt-2 font-mono text-xs text-slate-500">{cache.unmappedRepositorySlugs.join(", ")}</p></details>}<button type="button" onClick={() => void sync()} disabled={syncing} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-slate-100 px-3.5 py-2.5 text-sm font-semibold text-slate-950 transition hover:bg-white disabled:cursor-not-allowed disabled:opacity-60"><RefreshCw size={16} className={syncing ? "animate-spin" : ""} />{syncing ? "Syncing GitHub…" : "Sync Now"}</button></section>;
}
